//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DVD-Rom.
        /// </summary>
        public static string DriveTypeAsExtension_DVD {
            get {
                return ResourceManager.GetString("DriveTypeAsExtension.DVD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hard disk.
        /// </summary>
        public static string DriveTypeAsExtension_Hard {
            get {
                return ResourceManager.GetString("DriveTypeAsExtension.Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Network drive.
        /// </summary>
        public static string DriveTypeAsExtension_Network {
            get {
                return ResourceManager.GetString("DriveTypeAsExtension.Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Removable storage drive.
        /// </summary>
        public static string DriveTypeAsExtension_Removable {
            get {
                return ResourceManager.GetString("DriveTypeAsExtension.Removable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unknown drive.
        /// </summary>
        public static string DriveTypeAsExtension_Unknown {
            get {
                return ResourceManager.GetString("DriveTypeAsExtension.Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bitmap.
        /// </summary>
        public static string Extension_BMP {
            get {
                return ResourceManager.GetString("Extension.BMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dynamic link library.
        /// </summary>
        public static string Extension_DLL {
            get {
                return ResourceManager.GetString("Extension.DLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application.
        /// </summary>
        public static string Extension_EXE {
            get {
                return ResourceManager.GetString("Extension.EXE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File Folder.
        /// </summary>
        public static string Extension_Folder {
            get {
                return ResourceManager.GetString("Extension.Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GIF image.
        /// </summary>
        public static string Extension_GIF {
            get {
                return ResourceManager.GetString("Extension.GIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Setup information.
        /// </summary>
        public static string Extension_INF {
            get {
                return ResourceManager.GetString("Extension.INF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Initialization file.
        /// </summary>
        public static string Extension_INI {
            get {
                return ResourceManager.GetString("Extension.INI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Jpeg image.
        /// </summary>
        public static string Extension_JPG {
            get {
                return ResourceManager.GetString("Extension.JPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MIDI file.
        /// </summary>
        public static string Extension_MIDI {
            get {
                return ResourceManager.GetString("Extension.MIDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Music file.
        /// </summary>
        public static string Extension_MP3_AAC_WMA {
            get {
                return ResourceManager.GetString("Extension.MP3/AAC/WMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Windows package installer.
        /// </summary>
        public static string Extension_MSI {
            get {
                return ResourceManager.GetString("Extension.MSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Font file.
        /// </summary>
        public static string Extension_OTF_TTF {
            get {
                return ResourceManager.GetString("Extension.OTF/TTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Portable network graphics image.
        /// </summary>
        public static string Extension_PNG {
            get {
                return ResourceManager.GetString("Extension.PNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rich text document.
        /// </summary>
        public static string Extension_RTF {
            get {
                return ResourceManager.GetString("Extension.RTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на System file.
        /// </summary>
        public static string Extension_SYS {
            get {
                return ResourceManager.GetString("Extension.SYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text file.
        /// </summary>
        public static string Extension_TXT {
            get {
                return ResourceManager.GetString("Extension.TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unknown file.
        /// </summary>
        public static string Extension_Unknown {
            get {
                return ResourceManager.GetString("Extension.Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sound file.
        /// </summary>
        public static string Extension_WAV {
            get {
                return ResourceManager.GetString("Extension.WAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на B.
        /// </summary>
        public static string ModelLength_Size_Byte {
            get {
                return ResourceManager.GetString("ModelLength.Size.Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GB.
        /// </summary>
        public static string ModelLength_Size_GByte {
            get {
                return ResourceManager.GetString("ModelLength.Size.GByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на KB.
        /// </summary>
        public static string ModelLength_Size_KByte {
            get {
                return ResourceManager.GetString("ModelLength.Size.KByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MB.
        /// </summary>
        public static string ModelLength_Size_MByte {
            get {
                return ResourceManager.GetString("ModelLength.Size.MByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TB.
        /// </summary>
        public static string ModelLength_Size_TByte {
            get {
                return ResourceManager.GetString("ModelLength.Size.TByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на my Computer.
        /// </summary>
        public static string SystemFolder_Computer {
            get {
                return ResourceManager.GetString("SystemFolder.Computer", resourceCulture);
            }
        }
    }
}
