//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Locale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Locale.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitmap image.
        /// </summary>
        public static string FileSystem_Extension_BMP {
            get {
                return ResourceManager.GetString("FileSystem|Extension|BMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File folder.
        /// </summary>
        public static string FileSystem_Extension_Directory {
            get {
                return ResourceManager.GetString("FileSystem|Extension|Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic link library.
        /// </summary>
        public static string FileSystem_Extension_DLL {
            get {
                return ResourceManager.GetString("FileSystem|Extension|DLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVD-ROM.
        /// </summary>
        public static string FileSystem_Extension_Drive_CD_DVD {
            get {
                return ResourceManager.GetString("FileSystem|Extension|Drive|CD-DVD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard drive.
        /// </summary>
        public static string FileSystem_Extension_Drive_HDD {
            get {
                return ResourceManager.GetString("FileSystem|Extension|Drive|HDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network drive.
        /// </summary>
        public static string FileSystem_Extension_Drive_Network {
            get {
                return ResourceManager.GetString("FileSystem|Extension|Drive|Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removable storage.
        /// </summary>
        public static string FileSystem_Extension_Drive_REMOVABLE {
            get {
                return ResourceManager.GetString("FileSystem|Extension|Drive|REMOVABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Drive.
        /// </summary>
        public static string FileSystem_Extension_Drive_Unknown {
            get {
                return ResourceManager.GetString("FileSystem|Extension|Drive|Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string FileSystem_Extension_EXE {
            get {
                return ResourceManager.GetString("FileSystem|Extension|EXE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animated gif image.
        /// </summary>
        public static string FileSystem_Extension_GIF {
            get {
                return ResourceManager.GetString("FileSystem|Extension|GIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web page markup.
        /// </summary>
        public static string FileSystem_Extension_HTML {
            get {
                return ResourceManager.GetString("FileSystem|Extension|HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string FileSystem_Extension_ICO {
            get {
                return ResourceManager.GetString("FileSystem|Extension|ICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup configuration file.
        /// </summary>
        public static string FileSystem_Extension_INF {
            get {
                return ResourceManager.GetString("FileSystem|Extension|INF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization info file.
        /// </summary>
        public static string FileSystem_Extension_INI {
            get {
                return ResourceManager.GetString("FileSystem|Extension|INI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string FileSystem_Extension_JPG {
            get {
                return ResourceManager.GetString("FileSystem|Extension|JPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string FileSystem_Extension_Link {
            get {
                return ResourceManager.GetString("FileSystem|Extension|Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midi file.
        /// </summary>
        public static string FileSystem_Extension_MIDI {
            get {
                return ResourceManager.GetString("FileSystem|Extension|MIDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music file.
        /// </summary>
        public static string FileSystem_Extension_MP3_AAC {
            get {
                return ResourceManager.GetString("FileSystem|Extension|MP3-AAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows installer file.
        /// </summary>
        public static string FileSystem_Extension_MSI {
            get {
                return ResourceManager.GetString("FileSystem|Extension|MSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File .PNG.
        /// </summary>
        public static string FileSystem_Extension_PNG {
            get {
                return ResourceManager.GetString("FileSystem|Extension|PNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rich text document.
        /// </summary>
        public static string FileSystem_Extension_RTF {
            get {
                return ResourceManager.GetString("FileSystem|Extension|RTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        public static string FileSystem_Extension_Storage_Default {
            get {
                return ResourceManager.GetString("FileSystem|Extension|Storage|Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System file.
        /// </summary>
        public static string FileSystem_Extension_SYS {
            get {
                return ResourceManager.GetString("FileSystem|Extension|SYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text document.
        /// </summary>
        public static string FileSystem_Extension_TXT {
            get {
                return ResourceManager.GetString("FileSystem|Extension|TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FileSystem_Extension_UnknownFile {
            get {
                return ResourceManager.GetString("FileSystem|Extension|UnknownFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave sound.
        /// </summary>
        public static string FileSystem_Extension_WAV {
            get {
                return ResourceManager.GetString("FileSystem|Extension|WAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows media audio file.
        /// </summary>
        public static string FileSystem_Extension_WMA {
            get {
                return ResourceManager.GetString("FileSystem|Extension|WMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows markup file.
        /// </summary>
        public static string FileSystem_Extension_XAML {
            get {
                return ResourceManager.GetString("FileSystem|Extension|XAML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        public static string FileSystem_Extension_XML {
            get {
                return ResourceManager.GetString("FileSystem|Extension|XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string FileSystem_Size_B {
            get {
                return ResourceManager.GetString("FileSystem|Size|B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        public static string FileSystem_Size_GB {
            get {
                return ResourceManager.GetString("FileSystem|Size|GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        public static string FileSystem_Size_KB {
            get {
                return ResourceManager.GetString("FileSystem|Size|KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        public static string FileSystem_Size_MB {
            get {
                return ResourceManager.GetString("FileSystem|Size|MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TB.
        /// </summary>
        public static string FileSystem_Size_TB {
            get {
                return ResourceManager.GetString("FileSystem|Size|TB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Computer.
        /// </summary>
        public static string Storage_Object_Names_Computer {
            get {
                return ResourceManager.GetString("Storage|Object|Names|Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string Storage_Object_Names_Downloads {
            get {
                return ResourceManager.GetString("Storage|Object|Names|Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Pictures &amp; Video.
        /// </summary>
        public static string Storage_Object_Names_PicturesVideoLibrary {
            get {
                return ResourceManager.GetString("Storage|Object|Names|PicturesVideoLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Aquilion Data.
        /// </summary>
        public static string Storage_PhysicalDirectories_Names_ApplicationLocalDirectory {
            get {
                return ResourceManager.GetString("Storage|PhysicalDirectories|Names|ApplicationLocalDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Documents.
        /// </summary>
        public static string Storage_PhysicalDirectories_Names_MyDocuments {
            get {
                return ResourceManager.GetString("Storage|PhysicalDirectories|Names|MyDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Music.
        /// </summary>
        public static string Storage_PhysicalDirectories_Names_MyMusic {
            get {
                return ResourceManager.GetString("Storage|PhysicalDirectories|Names|MyMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Pictures.
        /// </summary>
        public static string Storage_PhysicalDirectories_Names_MyPictures {
            get {
                return ResourceManager.GetString("Storage|PhysicalDirectories|Names|MyPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Pictures.
        /// </summary>
        public static string Storage_PhysicalDirectories_Names_MyVideos {
            get {
                return ResourceManager.GetString("Storage|PhysicalDirectories|Names|MyVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Storage_PhysicalDirectories_Names_UserDirectory {
            get {
                return ResourceManager.GetString("Storage|PhysicalDirectories|Names|UserDirectory", resourceCulture);
            }
        }
    }
}
