//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Locale {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Locale.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bitmap image.
        /// </summary>
        public static string FileSystem_Extension_BMP {
            get {
                return ResourceManager.GetString("FileSystem|Extension|BMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File folder.
        /// </summary>
        public static string FileSystem_Extension_Directory {
            get {
                return ResourceManager.GetString("FileSystem|Extension|Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dynamic link library.
        /// </summary>
        public static string FileSystem_Extension_DLL {
            get {
                return ResourceManager.GetString("FileSystem|Extension|DLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DVD-ROM.
        /// </summary>
        public static string FileSystem_Extension_Drive_CD_DVD {
            get {
                return ResourceManager.GetString("FileSystem|Extension|Drive|CD-DVD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hard drive.
        /// </summary>
        public static string FileSystem_Extension_Drive_HDD {
            get {
                return ResourceManager.GetString("FileSystem|Extension|Drive|HDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Network drive.
        /// </summary>
        public static string FileSystem_Extension_Drive_Network {
            get {
                return ResourceManager.GetString("FileSystem|Extension|Drive|Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Removable storage.
        /// </summary>
        public static string FileSystem_Extension_Drive_REMOVABLE {
            get {
                return ResourceManager.GetString("FileSystem|Extension|Drive|REMOVABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unknown Drive.
        /// </summary>
        public static string FileSystem_Extension_Drive_Unknown {
            get {
                return ResourceManager.GetString("FileSystem|Extension|Drive|Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application.
        /// </summary>
        public static string FileSystem_Extension_EXE {
            get {
                return ResourceManager.GetString("FileSystem|Extension|EXE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Animated gif image.
        /// </summary>
        public static string FileSystem_Extension_GIF {
            get {
                return ResourceManager.GetString("FileSystem|Extension|GIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Web page markup.
        /// </summary>
        public static string FileSystem_Extension_HTML {
            get {
                return ResourceManager.GetString("FileSystem|Extension|HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Icon.
        /// </summary>
        public static string FileSystem_Extension_ICO {
            get {
                return ResourceManager.GetString("FileSystem|Extension|ICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Setup configuration file.
        /// </summary>
        public static string FileSystem_Extension_INF {
            get {
                return ResourceManager.GetString("FileSystem|Extension|INF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Initialization info file.
        /// </summary>
        public static string FileSystem_Extension_INI {
            get {
                return ResourceManager.GetString("FileSystem|Extension|INI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Image.
        /// </summary>
        public static string FileSystem_Extension_JPG {
            get {
                return ResourceManager.GetString("FileSystem|Extension|JPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Link.
        /// </summary>
        public static string FileSystem_Extension_Link {
            get {
                return ResourceManager.GetString("FileSystem|Extension|Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Midi file.
        /// </summary>
        public static string FileSystem_Extension_MIDI {
            get {
                return ResourceManager.GetString("FileSystem|Extension|MIDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Music file.
        /// </summary>
        public static string FileSystem_Extension_MP3_AAC {
            get {
                return ResourceManager.GetString("FileSystem|Extension|MP3-AAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File .PNG.
        /// </summary>
        public static string FileSystem_Extension_PNG {
            get {
                return ResourceManager.GetString("FileSystem|Extension|PNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rich text document.
        /// </summary>
        public static string FileSystem_Extension_RTF {
            get {
                return ResourceManager.GetString("FileSystem|Extension|RTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Storage.
        /// </summary>
        public static string FileSystem_Extension_Storage_Default {
            get {
                return ResourceManager.GetString("FileSystem|Extension|Storage|Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на System file.
        /// </summary>
        public static string FileSystem_Extension_SYS {
            get {
                return ResourceManager.GetString("FileSystem|Extension|SYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text document.
        /// </summary>
        public static string FileSystem_Extension_TXT {
            get {
                return ResourceManager.GetString("FileSystem|Extension|TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File.
        /// </summary>
        public static string FileSystem_Extension_UnknownFile {
            get {
                return ResourceManager.GetString("FileSystem|Extension|UnknownFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wave sound.
        /// </summary>
        public static string FileSystem_Extension_WAV {
            get {
                return ResourceManager.GetString("FileSystem|Extension|WAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Windows media audio file.
        /// </summary>
        public static string FileSystem_Extension_WMA {
            get {
                return ResourceManager.GetString("FileSystem|Extension|WMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Windows markup file.
        /// </summary>
        public static string FileSystem_Extension_XAML {
            get {
                return ResourceManager.GetString("FileSystem|Extension|XAML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на XML.
        /// </summary>
        public static string FileSystem_Extension_XML {
            get {
                return ResourceManager.GetString("FileSystem|Extension|XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на B.
        /// </summary>
        public static string FileSystem_Size_B {
            get {
                return ResourceManager.GetString("FileSystem|Size|B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GB.
        /// </summary>
        public static string FileSystem_Size_GB {
            get {
                return ResourceManager.GetString("FileSystem|Size|GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на KB.
        /// </summary>
        public static string FileSystem_Size_KB {
            get {
                return ResourceManager.GetString("FileSystem|Size|KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MB.
        /// </summary>
        public static string FileSystem_Size_MB {
            get {
                return ResourceManager.GetString("FileSystem|Size|MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TB.
        /// </summary>
        public static string FileSystem_Size_TB {
            get {
                return ResourceManager.GetString("FileSystem|Size|TB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My Computer.
        /// </summary>
        public static string Storage_Object_Names_Computer {
            get {
                return ResourceManager.GetString("Storage|Object|Names|Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Downloads.
        /// </summary>
        public static string Storage_Object_Names_Downloads {
            get {
                return ResourceManager.GetString("Storage|Object|Names|Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My Pictures &amp; Video.
        /// </summary>
        public static string Storage_Object_Names_PicturesVideoLibrary {
            get {
                return ResourceManager.GetString("Storage|Object|Names|PicturesVideoLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Local Aquilion Data.
        /// </summary>
        public static string Storage_PhysicalDirectories_Names_ApplicationLocalDirectory {
            get {
                return ResourceManager.GetString("Storage|PhysicalDirectories|Names|ApplicationLocalDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My Documents.
        /// </summary>
        public static string Storage_PhysicalDirectories_Names_MyDocuments {
            get {
                return ResourceManager.GetString("Storage|PhysicalDirectories|Names|MyDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My Music.
        /// </summary>
        public static string Storage_PhysicalDirectories_Names_MyMusic {
            get {
                return ResourceManager.GetString("Storage|PhysicalDirectories|Names|MyMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My Pictures.
        /// </summary>
        public static string Storage_PhysicalDirectories_Names_MyPictures {
            get {
                return ResourceManager.GetString("Storage|PhysicalDirectories|Names|MyPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My Pictures.
        /// </summary>
        public static string Storage_PhysicalDirectories_Names_MyVideos {
            get {
                return ResourceManager.GetString("Storage|PhysicalDirectories|Names|MyVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home.
        /// </summary>
        public static string Storage_PhysicalDirectories_Names_UserDirectory {
            get {
                return ResourceManager.GetString("Storage|PhysicalDirectories|Names|UserDirectory", resourceCulture);
            }
        }
    }
}
